### ISSUE TITLE
assistant not running

### ISSUE THREAD

**Issue by Priyajit08** [shivasiddharth/GassistPi#106]
when i try to run google samples assistant pushtotalk i get this error:
Traceback (most recent call last):
  File "/home/pi/env/bin/googlesamples-assistant-pushtotalk", line 11, in <module>
    sys.exit(main())
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 332, in main
    flush_size=audio_flush_size
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 187, in __init__
    blocksize=int(block_size/2),  # blocksize is in number of frames.
  File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 1256, in __init__
    **_remove_self(locals()))
  File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 673, in __init__
    samplerate)
  File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 2481, in _get_stream_parameters
    info = query_devices(device)
  File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 480, in query_devices
    raise PortAudioError('Error querying device {0}'.format(device))
sounddevice.PortAudioError: Error querying device -1

i am running it by giving:  googlesamples-assistant-pushtotalk --project-id $projid --device-model-id $modelid

**Comment by shivasiddharth** [comment]
Can you check your asoundrc and asound.conf ? Contents of both should be same.
