### ISSUE TITLE
Executing installer returns error.

### ISSUE THREAD

**Issue by nadunchandrabahu** [shivasiddharth/GassistPi#1145]
**IMPORTANT NOTICE  
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.**  

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**    

### Which branch of GassistPi are you using ?

I'm using the master branch.

### Board and OS details:    
Open a terminal and run   
```
cat /proc/cpuinfo  
cat /etc/os-release  
cat /etc/rpi-issue
```
```
Paste your Board and OS details here.   

processor	: 0
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2711
Revision	: c03114
Serial		: 100000008e8b8abc
Model		: Raspberry Pi 4 Model B Rev 1.4

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Raspberry Pi reference 2021-12-02
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, fa45ccf5a4b183ee566b36d74fb4b65bf9358bed, stage4

```

### Describe the bug:

```

When I run step 3.3 Execute the installer,
sudo  ./GassistPi/scripts/gassist-installer.sh
I'm able to enter the path to the .json file, project ID and Model ID. The installer runs for quite a while and stops when it gets to an error: Preparing metadata (setup.py) ... error, followed by details of error in red text.

```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues)?
Yes, I didn't find any questions asked about it.

### 2. Is the issue related to assistant installation ?
Yes

### If answer to question 2 is Yes, then attach the contents of terminal as a file or paste it below.
```
Enter the your full credential file name including the path and .json extension: /home/pi/client_secret_483864281700-b61equ0fi4e8l30jme19n3lin6ck0g6a.apps.googleusercontent.com.json

Enter the your Google Cloud Console Project-Id: united-time-225110

Enter the modelid that was generated in the actions console: united-time-225110-rpi-google-assistant-v1-8kse4s

Hit:1 http://archive.raspberrypi.org/debian buster InRelease                   
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease                
Hit:3 https://deb.nodesource.com/node_14.x buster InRelease     
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
autoconf is already the newest version (2.69-11).
automake is already the newest version (1:1.16.1-4).
bison is already the newest version (2:3.3.2.dfsg-1).
build-essential is already the newest version (12.6).
gcc is already the newest version (4:8.3.0-1+rpi2).
git is already the newest version (1:2.20.1-2+deb10u3).
libatlas-base-dev is already the newest version (3.10.3-8+rpi1).
libffi-dev is already the newest version (3.2.1-9).
libjack-jackd2-dev is already the newest version (1.9.12~dfsg-2).
libmpg123-dev is already the newest version (1.25.10-2).
libpcre3 is already the newest version (2:8.39-12).
libpcre3-dev is already the newest version (2:8.39-12).
libsox-fmt-mp3 is already the newest version (14.4.2+git20190427-1).
libssl-dev is already the newest version (1.1.1d-0+deb10u7).
libxml2-dev is already the newest version (2.9.4+dfsg1-7+deb10u2).
libxslt1-dev is already the newest version (1.1.32-2.2~deb10u1).
mpg123 is already the newest version (1.25.10-2).
mplayer is already the newest version (2:1.3.0-8+b5).
mpv is already the newest version (0.29.1-1).
nmap is already the newest version (7.70+dfsg1-6+deb10u2).
portaudio19-dev is already the newest version (19.6.0-1+deb10u1).
python is already the newest version (2.7.16-1).
python-dev is already the newest version (2.7.16-1).
python-setuptools is already the newest version (40.8.0-1).
python3 is already the newest version (3.7.3-1).
python3-dev is already the newest version (3.7.3-1).
python3-lxml is already the newest version (4.3.2-1+deb10u3).
python3-setuptools is already the newest version (40.8.0-1).
python3-venv is already the newest version (3.7.3-1).
socat is already the newest version (1.7.3.2-2).
sox is already the newest version (14.4.2+git20190427-1).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-1).
python-pip is already the newest version (18.1-5+rpt1).
python3-pip is already the newest version (18.1-5+rpt1).
vlc is already the newest version (3.0.12-0+deb10u1+rpt3).
The following package was automatically installed and is no longer required:
  uuid-dev
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Checking OS Compatability


You are running the installer on Buster


Your board supports Ok-Google Hotword. You can also trigger the assistant using custom-wakeword


GPIO pins can be used with the assistant


Copying Snowboy files to GassistPi directory


Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pip in ./env/lib/python3.7/site-packages (21.3.1)
Requirement already satisfied: setuptools in ./env/lib/python3.7/site-packages (59.6.0)
Requirement already satisfied: wheel in ./env/lib/python3.7/site-packages (0.37.0)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/shivasiddharth/pafy.git (from -r /home/pi/GassistPi/Requirements/GassistPi-pip-requirements.txt (line 9))
  Cloning https://github.com/shivasiddharth/pafy.git to /tmp/pip-req-build-ub_hnk12
  Running command git clone --filter=blob:none -q https://github.com/shivasiddharth/pafy.git /tmp/pip-req-build-ub_hnk12
  Resolved https://github.com/shivasiddharth/pafy.git to commit 45f0deb067bf7c420cdf83a0529fd5274c12de18
  Preparing metadata (setup.py) ... error
  **ERROR: Command errored out with exit status 1:
   command: /home/pi/env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ub_hnk12/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ub_hnk12/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-u48rt6_5
       cwd: /tmp/pip-req-build-ub_hnk12/
  Complete output (16 lines):
  Traceback (most recent call last):
    File "/tmp/pip-req-build-ub_hnk12/pafy/pafy.py", line 48, in <module>
      import youtube_dl
  ModuleNotFoundError: No module named 'youtube_dl'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-ub_hnk12/setup.py", line 13, in <module>
      from pafy import __version__
    File "/tmp/pip-req-build-ub_hnk12/pafy/__init__.py", line 7, in <module>
      from .pafy import new
    File "/tmp/pip-req-build-ub_hnk12/pafy/pafy.py", line 52, in <module>
      "pafy: youtube-dl not found; you can use the internal backend by "
  ImportError: pafy: youtube-dl not found; you can use the internal backend by setting the environmental variable PAFY_BACKEND to "internal". It is not enabled by default because it is not as well maintained as the youtube-dl backend.
  ----------------------------------------
WARNING: Discarding git+https://github.com/shivasiddharth/pafy.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.**


```

### 3. Does the assistant service start normally?
Yes/No

### 4. Is the assistant service restarting automatically?
Yes/No

### If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

**Comment by shivasiddharth** [comment]
Couple of things:
1. https://deb.nodesource.com/node_14.x is not in the offical sources list.
2. Is that 64 bit version of OS or 32 bit ?

**Comment by nadunchandrabahu** [comment]
Hi,

1. OK I see, what can I do to fix that? And what is the "official sources list"?, I've only been referring to your GitHub page and GassistPi documentation, is there another source? (Sorry for the newbie questions)
2. It's the 32 bit version, do I need to use the 64 bit OS?

Thank you for all your work.

**Comment by shivasiddharth** [comment]
Do: 
```
sudo nano /etc/apt/sources.list
```
Share the output of what you are seeing.

**Comment by nadunchandrabahu** [comment]
![output1](https://user-images.githubusercontent.com/96213950/146488504-0613bd66-cef8-45b5-822b-1a75407995c8.png)
^ this is what I'm seeing

**Comment by shivasiddharth** [comment]
In the pip requirements file, change the line ```git+https://github.com/shivasiddharth/pafy.git``` to ```pafy``` And then try again.

**Comment by nadunchandrabahu** [comment]
@shivasiddharth Installation works now! Thank you so much for your help.

**Comment by shivasiddharth** [comment]
Will close this issue. But consider using a newer version of the OS. What you are using is a year old.

**Comment by shivasiddharth** [comment]
Apologies. My bad ! I saw that as i did not see the 2021 properly in the realse date.

**Comment by nadunchandrabahu** [comment]
@shivasiddharth it is infact the year old OS I'm using now, that is Raspbian Buster. I was using Bullseye, the latest OS and still running into issues, and since your guide says to use either Raspbian Stretch or Buster, I switched to buster. I plan on switching to the newer OS and testing it out with the above fix, though I recall running into a different set of issues on there as well.

**Comment by shivasiddharth** [comment]
Right now Bullseye has a lot of problems. Thats why Raspberry Pi foundation has rolled back to a legacy version. If you want to try the Bullseye version, git clone the Snowboy-Elim branch. That works with Raspbian Bullseye 32 bit.

Instead of ```git clone https://github.com/shivasiddharth/GassistPi``` 
use ```git clone https://github.com/shivasiddharth/GassistPi -b Snowboy-Elim```  

Other than this minor change, rest all the steps are same from the guide.

**Comment by nadunchandrabahu** [comment]
I see, thank you.
