### ISSUE TITLE
Timeout on downloading youtube_dl-2018.2.11-py2.py3-none-any.whl during installation

### ISSUE THREAD

**Issue by chsims1** [shivasiddharth/GassistPi#210]
Collecting youtube_dl>=2018.1.27 (from -r /home/pi/GassistPi/Requirements/GassistPi-pip-requirements.txt (line 10))
  Downloading youtube_dl-2018.2.11-py2.py3-none-any.whl (1.7MB)
Exception:
Traceback (most recent call last):                                            
  File "/home/pi/env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 298, in _error_catcher                              
    yield                                                                     
  File "/home/pi/env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 380, in read                                        
    data = self._fp.read(amt)                                                 
  File "/home/pi/env/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 60, in read                            
    data = self.__fp.read(amt)                                                
  File "/usr/lib/python3.5/http/client.py", line 448, in read                 
    n = self.readinto(b)                                                      
  File "/usr/lib/python3.5/http/client.py", line 488, in readinto             
    n = self.fp.readinto(b)                                                   
  File "/usr/lib/python3.5/socket.py", line 576, in readinto                  
    return self._sock.recv_into(b)                                            
  File "/usr/lib/python3.5/ssl.py", line 937, in recv_into                    
    return self.read(nbytes, buffer)                                          
  File "/usr/lib/python3.5/ssl.py", line 799, in read                         
    return self._sslobj.read(len, buffer)                                     
  File "/usr/lib/python3.5/ssl.py", line 583, in read                         
    v = self._sslobj.read(len, buffer)                                        
socket.timeout: The read operation timed out

**Comment by chsims1** [comment]
Yep, works ty.
