### ISSUE TITLE
Exception during gassist-installer-pi-zero.sh

### ISSUE THREAD

**Issue by sevenmiletechnology** [shivasiddharth/GassistPi#245]
Error
Collecting gmusicapi>=11.0.0 (from -r /home/pi/GassistPi/Requirements/GassistPi-pip-requirements.txt (line 6))
Exception:
Traceback (most recent call last):
  File "/home/pi/env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/home/pi/env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 391, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/pi/env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

Run on Raspberry Pi B+

**Comment by sevenmiletechnology** [comment]
I removed the gmusic reference from the requirements.txt file and got the same error on another line
