### ISSUE TITLE
"What's in the news" crashes/restarts assistant service

### ISSUE THREAD

**Issue by PalasX** [shivasiddharth/GassistPi#257]
Expected behavior:
Asking "What's in the news?" results in the standard google assistant news feed, as with any other device linked to your google account's assistant.

Actual behavior:
No answer to the question, followed by a about 5 seconds of silence, then the GassistPi startup sound. AKA, the service crashes and then restarts.

Log:
2018-03-07 17:57:36,273 ERROR __main__ local variable 'URL' referenced before assignment
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 479, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 377, in main
    feed(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 293, in feed
    feed=feedparser.parse(URL)
UnboundLocalError: local variable 'URL' referenced before assignment
2018-03-07 17:57:43,140 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-03-07 17:57:43,145 DEBUG requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com
2018-03-07 17:57:43,343 DEBUG requests.packages.urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None

Is there some technical reason that we cannot use the standard news reading feature of the google assistant?

**Comment by shivasiddharth** [comment]
I have used the "News" as a keyword for RSS Feed Streaming (https://github.com/shivasiddharth/GassistPi#rss-feeds-streaming).  Either you can change the keyword in main.py or remove `'news'.lower() in str(usrcmd).lower() or` in the main.py
