### ISSUE TITLE
No welcome message and cant start gassistpi manually

### ISSUE THREAD

**Issue by amyth1884** [shivasiddharth/GassistPi#415]
### Describe the bug:
```
I had installed gassistpi once before and it was working well, recently I had formatted my sd card and tried reinstalling gassistpi but now I dont get the welcome message or the beep when gassist pi is ready to listen to command after hotword.

```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
Yes

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```
pi@BarryPai:~ $ /home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --device_model_id barrypai-52400-barrypai-9tu9dg
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 34, in <module>
    from actions import say
  File "/home/pi/GassistPi/src/actions.py", line 50, in <module>
    credentials = oauth2.SpotifyClientCredentials(client_id=client_id, client_secret=client_secret)
NameError: name 'client_id' is not defined
pi@BarryPai:~ $

```

### 3. Does the assistant service start normally?
No
Cant tell as there is no response 
### 4. Is the assistant service restarting automatically?
No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```
pi@BarryPai:~ $ /home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --device_model_id barrypai-52400-barrypai-9tu9dg
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 34, in <module>
    from actions import say
  File "/home/pi/GassistPi/src/actions.py", line 50, in <module>
    credentials = oauth2.SpotifyClientCredentials(client_id=client_id, client_secret=client_secret)
NameError: name 'client_id' is not defined
pi@BarryPai:~ $

```

### Paste the contents of the terminal below
```

```

**Comment by shivasiddharth** [comment]
Fixed [in](https://github.com/shivasiddharth/GassistPi/commit/87195aae07177315fe256f80fd5750de5c83dfca)
