### ISSUE TITLE
rpi zero w setup issue

### ISSUE THREAD

**Issue by rohit366** [shivasiddharth/GassistPi#442]
### Describe the bug:
```
I have followed the instruction as per your readme guild for rpi zero w but I am getting an error on the last step.

all the above steps have been finished successfully. The log for the error I am getting is provided in the below section.
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).

Yes

### 2. Is the issue related to assistant installation ?

Yes

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```
pi@raspberrypi:/env/bin $ python3 -u /home/pi/GassistPi/src/pushbutton.py --project-id rpi-assistant-207815 --device-model-id rpi-assistant-207815-rpi-zero-fzkpjy
Traceback (most recent call last):
File "/home/pi/GassistPi/src/pushbutton.py", line 30, in 
import grpc
ImportError: No module named 'grpc'
pi@raspberrypi:/env/bin $ python -u /home/pi/GassistPi/src/pushbutton.py --project-id rpi-assistant-207815 --device-model-id rpi-assistant-207815-rpi-zero-fzkpjy
Traceback (most recent call last):
File "/home/pi/GassistPi/src/pushbutton.py", line 35, in 
from actions import say
File "/home/pi/GassistPi/src/actions.py", line 1216
SyntaxError: Non-ASCII character '\xc3' in file /home/pi/GassistPi/src/actions.py on line 1216, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

### 3. Does the assistant service start normally?

No

### 4. Is the assistant service restarting automatically?

No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```
/home/pi/env/bin/python3 -u /home/pi/GassistPi/src/pushbutton.py --project-id rpi-assistant-207815 --device-model-id rpi-assistant-207815-rpi-zero-fzkpjy
```

### Paste the contents of the terminal below
```
Illegal instruction
```

### Attach the log file. Log file can be found in /tmp directory. Remeber to copy your log file before shutting down or restarting the Pi.

**Comment by rohit366** [comment]
even after exiting the environment I am getting the same warning.
