### ISSUE TITLE
GassistPi restart after attempt to stream music from YouTube

### ISSUE THREAD

**Issue by Nikodemski2002** [shivasiddharth/GassistPi#448]
### Describe the bug:
```
Hi! I have a problem with youtube music stream function. When i say "Hey google stream nina simone", the GA is saying "Playing nina simone"(I changed it from "Getting YouTube link", and its having this trouble, even before changing this phrase), and restart. Instead of music i hear startup music, and GA Hi. Yesterday, after quite attempts it works great, sometimes it crash, but always after crush it work for long time. But now it doesn't work completely.
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes, i read the issue #128 but nothing help me.

### 2. Is the issue related to assistant installation ?
No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes

### 4. Is the assistant service restarting automatically?
No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```
Hey google stream nina simone (or any other song)
```

### Paste the contents of the terminal below
```
ON_MUTED_CHANGED:
  {"is_muted": false}
ON_START_FINISHED

ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "stream Nina Simone"}
stopping vlc
Playing nina simone
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 983, in emit
    stream.write(msg)
UnicodeEncodeError: 'latin-1' codec can't encode character '\uff1f' in position 124: ordinal not in range(256)
Call stack:
  File "/home/pi/GassistPi/src/main.py", line 516, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 397, in main
    YouTube_No_Autoplay(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 977, in YouTube_No_Autoplay
    say("Playing" + track)
  File "/home/pi/GassistPi/src/actions.py", line 188, in say
    tts = gTTS(text=words, lang=language)
  File "/home/pi/env/lib/python3.5/site-packages/gtts/tts.py", line 108, in __init__
    log.debug("%s: %s", k, v)
Message: '%s: %s'
Arguments: ('tokenizer_func', <bound method Tokenizer.run of re.compile('(?<=\\?).|(?<=\\!).|(?<=\\\uff1f).|(?<=\\\uff01).|(?<!\\.[a-z])\\. |(?<!\\.[a-z])\\, |\\ˇ|\\]|\\\u060c|\\)|\\[|\\ż|\\\u2026|\\\u2014|\\\uff0c|\\\u2025|\\\u3002|\\:|\\\n|\\(|\\\uff1a|\\\u3001|\\;', re.IGNORECASE) from: [<function tone_marks at 0x727768a0>, <function period_comma at 0x727768e8>, <function other_punctuation at 0x72776930>]>)
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.23.8; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

Directory: /tmp/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: say.mp3 ...

MPEG 2.0 L III cbr32 24000 mono

[0:01] Decoding of say.mp3 finished.
nina simone
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

### Attach the log file. Log file can be found in /tmp directory. Remeber to copy your log file before shutting down or restarting the Pi.
[GassistPi.log](https://github.com/shivasiddharth/GassistPi/files/2218891/GassistPi.log)

**Comment by Nikodemski2002** [comment]
Edit. After 5:35 PM it started working normally, i recognized same behavior yesterday, when i came back home around 3:00 PM it started working normally until next day. And also now the spotify playing works(because earlier it doesn't work to). I don'd have any idea why it works so randomly. I check the google cloud console to check for errors, but there was no error there.

**Comment by shivasiddharth** [comment]
Seems like a temporary network issue to me. Can you try again and give it a shot ?

**Comment by Nikodemski2002** [comment]
By the way, I have two questions. First one - Is there any way to play next track from spotify playlist. Second - Is your project also support the sonoff dual?

**Comment by Nikodemski2002** [comment]
Ok. I will also try tomorrow, in the morning and also check spotify function.

**Comment by shivasiddharth** [comment]
Closing this for inactivity
