### ISSUE TITLE
Hi theres an issue in the latest version

### ISSUE THREAD

**Issue by AmirCrimson** [shivasiddharth/GassistPi#453]
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "what can you do"}
ON_RENDER_RESPONSE:
  {"text": "Here are some things you can ask for:", "type": 0}
ON_RENDER_RESPONSE:
  {"text": "Here are some things you can ask for:", "type": 0}
ON_RENDER_RESPONSE:
{
  "text": "Take a pick:\nTranslation · Sleep Timers ·  · Answers · Google Home · Calendar · Help · My Assistant · News ·  · Shopping · Sports · Timers · Weather ·  · Alarms ·  ·  · ",
  "type": 0
}
ON_RENDER_RESPONSE:
{
  "text": "Take a pick:\nTranslation · Sleep Timers ·  · Answers · Google Home · Calendar · Help · My Assistant · News ·  · Shopping · Sports · Timers · Weather ·  · Alarms ·  ·  · ",
  "type": 0
}
ERROR:__main__:local variable 'URL' referenced before assignment
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 560, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 454, in main
    feed(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 308, in feed
    feed=feedparser.parse(URL)
UnboundLocalError: local variable 'URL' referenced before assignment

**Comment by AmirCrimson** [comment]
the assistant freezes this way
service stays stuck
but manually im able to break it and run it again.
can you plz fix this problem???
