### ISSUE TITLE
 authorization code Issue

### ISSUE THREAD

**Issue by Zacki84** [shivasiddharth/GassistPi#476]
Hi

I have a problem with installtion of your project
I run the install script for rpi3 and everything runs perfect, no issue until the point where I should enter the authorization code:
the link above is not working: Error 500
where do I get this authorization code from???

Thanks

**Comment by juanmabernabeu** [comment]
Same issue here

**Comment by LordTyrion123** [comment]
I got the same issue when installing. I then realized that I had forgotten to enable the API and set Activity Control on the Google Actions Console from [here](https://developers.google.com/assistant/sdk/guides/library/python/embed/config-dev-project-and-account). Did you follow the steps exactly?

**Comment by Zacki84** [comment]
yeah, I solved it in the meantime, but this was exactly my problem. Thanks a lot!!!
but now I faced a new issue.
the demo test went pretty well, but when I want to start the assistant now, I get the following error:

[029a01e8] pulse audio output error: PulseAudio server connection failure: Connection refused
[028e3c68] pulse audio output error: PulseAudio server connection failure: Connection refused
Traceback (most recent call last):
File "/home/pi/GassistPi/src/snowboydetect.py", line 15, in swig_import_helper
return importlib.import_module(mname)
File "/usr/lib/python3.4/importlib/init.py", line 109, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
File "<frozen importlib._bootstrap>", line 1715, in load_module
File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/pi/GassistPi/src/main.py", line 57, in <module>
import snowboydecoder
File "/home/pi/GassistPi/src/snowboydecoder.py", line 5, in <module>
import snowboydetect
File "/home/pi/GassistPi/src/snowboydetect.py", line 18, in <module>
_snowboydetect = swig_import_helper()
File "/home/pi/GassistPi/src/snowboydetect.py", line 17, in swig_import_helper
return importlib.import_module('_snowboydetect')
File "/usr/lib/python3.4/importlib/init.py", line 109, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory

**Comment by shivasiddharth** [comment]
@Zacki84 , please do not post the same errors in multiple places. I am still looking at your issue, i need time.

**Comment by Zacki84** [comment]
Ok Sid, sorry.
I try to install it on a new formated sd, but I face the same issue. Thanks for helping me, I really want this assist and I can't wait to have it up and running ;-)
