### ISSUE TITLE
Demo Test OK - manually start failing

### ISSUE THREAD

**Issue by Zacki84** [shivasiddharth/GassistPi#482]
Hi

I installed the Gassist and the Demo Test went fine, but as soon as I want to start the Assist manually, I get the following error:
[028133e8] pulse audio output error: PulseAudio server connection failure: Connection refused
[02896db0] pulse audio output error: PulseAudio server connection failure: Connection refused
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/snowboydetect.py", line 15, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1715, in load_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 57, in <module>
    import snowboydecoder
  File "/home/pi/GassistPi/src/snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/home/pi/GassistPi/src/snowboydetect.py", line 18, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pi/GassistPi/src/snowboydetect.py", line 17, in swig_import_helper
    return importlib.import_module('_snowboydetect')
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory

How can I solve this?

**Comment by shivasiddharth** [comment]
Did you edit the config.yaml file to add your own custom wakewords ?

**Comment by Zacki84** [comment]
no, not at the moment, later the plan would be to change it.
thanks for helping me!!!!

**Comment by Zacki84** [comment]
Is there a chance to run it on jessie?

**Comment by shivasiddharth** [comment]
I have written all the codes and tested them on Stretch, so I don't support/troubleshoot Jessie.  If you are running a newer OS and if the project is on old OS then it would make sense. But in your case, its the other way around. Please try the stretch OS and still if you run into issues, then re-open this issue. Closing this untill then.

**Comment by Zacki84** [comment]
Hi Sid. I have some other skripts running parallel, but they are only running on
Jessie :( I tries to update but failed. 
Is there really no chance to get Gassist running on Jessie too? There must ba a chance. Thanks for your support
