### ISSUE TITLE
Python2 or Python3 Ambiguity (I think; installation error on pyaudio)

### ISSUE THREAD

**Issue by YangVincent** [shivasiddharth/GassistPi#507]
### Describe the bug:
```
Installing does not work because it confuses python2 and python3. 
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
Yes

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```
Enter the your full credential file name including the path and .json extension: <redacted>

Enter the your Google Cloud Console Project-Id: <redacted>

Enter the modelid that was generated in the actions console: <redacted>

Hit http://mirrordirector.raspbian.org wheezy Release.gpg
Hit http://archive.raspberrypi.org wheezy Release.gpg
Hit http://raspberrypi.collabora.com wheezy Release.gpg                              
Hit http://archive.raspberrypi.org wheezy Release                                    
Hit http://raspberrypi.collabora.com wheezy Release                                  
Hit http://mirrordirector.raspbian.org wheezy Release                 
Hit http://archive.raspberrypi.org wheezy/main armhf Packages         
Hit http://raspberrypi.collabora.com wheezy/rpi armhf Packages                       
Hit http://mirrordirector.raspbian.org wheezy/main armhf Packages                                                            
Hit http://mirrordirector.raspbian.org wheezy/contrib armhf Packages                                                           
Hit http://mirrordirector.raspbian.org wheezy/non-free armhf Packages                                                          
Hit http://mirrordirector.raspbian.org wheezy/rpi armhf Packages                         
Ign http://raspberrypi.collabora.com wheezy/rpi Translation-en_GB                        
Ign http://raspberrypi.collabora.com wheezy/rpi Translation-en     
Ign http://archive.raspberrypi.org wheezy/main Translation-en_GB   
Ign http://archive.raspberrypi.org wheezy/main Translation-en                      
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-en_GB                                                                                                                                                   
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-en               
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-en
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-en
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libjack-jackd2-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libffi-dev is already the newest version.
libssl-dev is already the newest version.
portaudio19-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Downloading/unpacking pyaudio
  Cannot fetch index base URL http://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement pyaudio
No distributions at all found for pyaudio
Storing complete log in /root/.pip/pip.log
```

### 3. Does the assistant service start normally?
Yes/No

### 4. Is the assistant service restarting automatically?
Yes/No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

### Attach the log file. Log file can be found in /tmp directory. Remeber to copy your log file before shutting down or restarting the Pi.

```
pi@raspberrypi ~ $ sudo cat /root/.pip/pip.log
------------------------------------------------------------
/usr/bin/pip run on Tue Aug 28 06:32:54 2018
Downloading/unpacking pyaudio

  Getting page http://pypi.python.org/simple/pyaudio
  Could not fetch URL http://pypi.python.org/simple/pyaudio: HTTP Error 403: SSL is required
  Will skip URL http://pypi.python.org/simple/pyaudio when looking for download links for pyaudio
  Getting page http://pypi.python.org/simple/
  Could not fetch URL http://pypi.python.org/simple/: HTTP Error 403: SSL is required
  Will skip URL http://pypi.python.org/simple/ when looking for download links for pyaudio
  Cannot fetch index base URL http://pypi.python.org/simple/

  URLs to search for versions for pyaudio:
  * http://pypi.python.org/simple/pyaudio/
  Getting page http://pypi.python.org/simple/pyaudio/
  Could not fetch URL http://pypi.python.org/simple/pyaudio/: HTTP Error 403: SSL is required
  Will skip URL http://pypi.python.org/simple/pyaudio/ when looking for download links for pyaudio
  Could not find any downloads that satisfy the requirement pyaudio

No distributions at all found for pyaudio

Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 978, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 157, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for pyaudio

```

**Comment by YangVincent** [comment]
I am on a Raspberry Pi 2

**Comment by YangVincent** [comment]
I was on Wheezy; would Jessie work or does it have to be Stretch?
