### ISSUE TITLE
Codec error

### ISSUE THREAD

**Issue by tvaneynde** [shivasiddharth/GassistPi#533]
### Describe the bug:
```
When i launch the assistant i get an error. I know this is an already discussed issue but the comments didn't help.
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
Yes

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```
Traceback (most recent call last):
  File "/home/pi/env/bin/googlesamples-assistant-hotword", line 11, in <module>
    sys.exit(main())
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/library/hotword.py", line 145, in main
    process_event(event)
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/library/hotword.py", line 59, in process_event
    print(event)
UnicodeEncodeError: 'latin-1' codec can't encode character '\U0001f333' in position 93: ordinal not in range(256)

```

### 3. Does the assistant service start normally?
Yes/No

### 4. Is the assistant service restarting automatically?
Yes/No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

**Comment by shivasiddharth** [comment]
Just give it some time. Its a network google cloud issue, will get resolved automatically.
