### ISSUE TITLE
NameError: name 'os' is not defined

### ISSUE THREAD

**Issue by arcao** [shivasiddharth/GassistPi#550]
I tried latest version 80234de569157fe3b31178b385308b782e09045f,  but it crash on start with:

```
pi@googleassistant:~ $ /home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --device_model_id saved-model-id
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 40, in <module>
    from actions import say
  File "/home/pi/GassistPi/src/actions.py", line 15, in <module>
    from mediaplayer import api
  File "/home/pi/GassistPi/src/mediaplayer.py", line 9, in <module>
    from youtube_search_engine import youtube_search
  File "/home/pi/GassistPi/src/youtube_search_engine.py", line 9, in <module>
    ROOT_PATH = os.path.realpath(os.path.join(__file__, '..', '..'))
NameError: name 'os' is not defined
```

After adding `import os` to `/home/pi/GassistPi/src/youtube_search_engine.py` it started to work.

**Comment by shivasiddharth** [comment]
Thanks for the shout. Its fixed.
