### ISSUE TITLE
parcel tracking goes wrong

### ISSUE THREAD

**Issue by aandroide** [shivasiddharth/GassistPi#553]
### Describe the bug:
```
{"text": "Where is my Parcel"}
ERROR:__main__:'Mobileclient' object has no attribute 'trackings'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 767, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 635, in main
    track()
  File "/home/pi/GassistPi/src/actions.py", line 346, in track
    text=api.trackings.get(tracking=dict(slug=slug, tracking_number=number))
AttributeError: 'Mobileclient' object has no attribute 'trackings'


```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
yes

### 2. Is the issue related to assistant installation ?
No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes

### 4. Is the assistant service restarting automatically?
No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

**Comment by shivasiddharth** [comment]
Have you added the aftership API in actions.py file ?

**Comment by aandroide** [comment]
Yes and i have uncomment 2 line

**Comment by aandroide** [comment]
thanks for the fix now works.
I just wanted to point out to you that in the readme file you wrote that the bees to trace the packages are inserted in config.yaml. while it should be inserted in the actions.py file currently.

**Comment by aandroide** [comment]
ok, i have created the pull request
