### ISSUE TITLE
error to play track from deezer 

### ISSUE THREAD

**Issue by xcybermanx** [shivasiddharth/GassistPi#603]
hello sir 

all is worked fine after edit gtoken.py youtube track & radio but in deezer i have error : 

(info) i have change deezer id like this   User_id: '2393187700'

```
ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "play playlist number 2 from Deezer"}
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "play playlist number 2 from Deezer"}
stopping vlc
/home/pi/env/lib/python3.5/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Getting links for playlist number 2
Getting links for playlist number 2
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
        version 1.23.8; written and copyright by Michael Hipp and others
        free software (LGPL) without any warranty but with best wishes

Directory: /tmp/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: say.mp3 ...

MPEG 2.0 L III cbr32 24000 mono

[0:02] Decoding of say.mp3 finished.
ERROR:__main__:[Errno 2] No such file or directory: '/tmp/say.mp3'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 666, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 658, in main
    deezer_playlist_select(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 1503, in deezer_playlist_select
    say("Getting links for playlist number " + playlistnumreq)
  File "/home/pi/GassistPi/src/actions.py", line 223, in say
    os.remove(ttsfilename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/say.mp3'
```

after this error raspberry freez & i need to restart it 

Thank You

**Comment by shivasiddharth** [comment]
https://github.com/shivasiddharth/GassistPi/issues/534#issuecomment-429357262
