### ISSUE TITLE
GassistPi restarts when i give commands from action.py [errors listed]

### ISSUE THREAD

**Issue by madmadda** [shivasiddharth/GassistPi#608]
### Describe the bug:
```
when i say e.g stream dancing in the rain , i dont get anything back and it reboots (it happens with everything with radio etc ) and this happened recently , it was working fine 3 months ago
NOTE : I didnt touch anything..
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes but nothing fixed the problem

### 2. Is the issue related to assistant installation ?
No cause the assistant works just perfect ,  (i can give her commnds and search on the web).

**### the temp file bellow :** 
2018-11-01 11:23:00,236 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 11:23:00,246 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 11:23:00,735 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-11-01 11:23:28,982 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-11-01 11:23:29,399 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2018-11-01 11:23:29,976 ERROR __main__ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 508, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 399, in main
    radio(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 222, in radio
    say("Tuning into " + name)
  File "/home/pi/GassistPi/src/actions.py", line 165, in say
    words= translator.translate(words, dest=language)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
2018-11-01 11:23:40,056 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 11:23:40,063 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 11:23:40,537 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-11-01 11:23:52,260 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-11-01 11:23:52,657 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2018-11-01 11:23:53,661 ERROR __main__ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 508, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 394, in main
    YouTube_No_Autoplay(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 1027, in YouTube_No_Autoplay
    say("Getting youtube link")
  File "/home/pi/GassistPi/src/actions.py", line 165, in say
    words= translator.translate(words, dest=language)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
2018-11-01 11:24:03,484 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 11:24:03,490 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 11:24:03,821 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-11-01 11:27:01,114 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 11:27:01,121 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 11:27:01,459 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-11-01 12:26:24,882 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-11-01 12:26:25,253 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2018-11-01 12:26:25,784 ERROR __main__ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 508, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 399, in main
    radio(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 222, in radio
    say("Tuning into " + name)
  File "/home/pi/GassistPi/src/actions.py", line 165, in say
    words= translator.translate(words, dest=language)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
2018-11-01 12:26:45,091 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 12:26:45,099 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 12:26:45,499 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-11-01 12:29:12,934 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-11-01 12:29:13,311 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2018-11-01 12:29:13,570 ERROR __main__ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 508, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 408, in main
    feed(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 295, in feed
    say(title)
  File "/home/pi/GassistPi/src/actions.py", line 165, in say
    words= translator.translate(words, dest=language)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
2018-11-01 12:30:08,022 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 12:30:08,028 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 12:30:08,458 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-11-01 12:30:19,335 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-11-01 12:30:19,686 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2018-11-01 12:30:19,877 ERROR __main__ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 508, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 408, in main
    feed(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 295, in feed
    say(title)
  File "/home/pi/GassistPi/src/actions.py", line 165, in say
    words= translator.translate(words, dest=language)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
2018-11-01 12:30:28,452 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 12:30:28,458 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 12:30:28,857 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-11-01 12:34:15,007 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-11-01 12:34:15,364 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2018-11-01 12:34:19,930 ERROR __main__ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 508, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 399, in main
    radio(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 222, in radio
    say("Tuning into " + name)
  File "/home/pi/GassistPi/src/actions.py", line 165, in say
    words= translator.translate(words, dest=language)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
2018-11-01 12:34:34,206 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 12:34:34,219 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 12:34:34,625 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-11-01 12:36:33,119 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 12:36:33,127 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 12:36:33,727 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-11-01 12:37:06,473 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-11-01 12:37:06,816 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2018-11-01 12:37:07,684 ERROR __main__ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 508, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 399, in main
    radio(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 222, in radio
    say("Tuning into " + name)
  File "/home/pi/GassistPi/src/actions.py", line 165, in say
    words= translator.translate(words, dest=language)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
2018-11-01 12:37:17,090 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-11-01 12:37:17,453 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2018-11-01 12:37:18,306 ERROR __main__ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 508, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 399, in main
    radio(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 222, in radio
    say("Tuning into " + name)
  File "/home/pi/GassistPi/src/actions.py", line 165, in say
    words= translator.translate(words, dest=language)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
2018-11-01 12:37:26,745 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 12:37:26,751 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 12:37:27,149 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-11-01 12:37:48,039 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 12:37:48,046 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 12:37:49,121 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-11-01 12:37:59,106 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-11-01 12:37:59,141 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-11-01 12:37:59,468 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2018-11-01 12:37:59,480 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2018-11-01 12:38:00,349 ERROR __main__ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 508, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 399, in main
    radio(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 222, in radio
    say("Tuning into " + name)
  File "/home/pi/GassistPi/src/actions.py", line 165, in say
    words= translator.translate(words, dest=language)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
2018-11-01 12:38:00,349 ERROR __main__ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 508, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 399, in main
    radio(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 222, in radio
    say("Tuning into " + name)
  File "/home/pi/GassistPi/src/actions.py", line 165, in say
    words= translator.translate(words, dest=language)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
2018-11-01 12:38:08,966 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 12:38:08,973 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 12:38:09,507 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-11-01 12:38:20,596 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-11-01 12:38:20,997 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2018-11-01 12:38:22,571 ERROR __main__ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 508, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 394, in main
    YouTube_No_Autoplay(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 1027, in YouTube_No_Autoplay
    say("Getting youtube link")
  File "/home/pi/GassistPi/src/actions.py", line 165, in say
    words= translator.translate(words, dest=language)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
2018-11-01 12:38:31,372 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 12:38:31,378 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 12:38:31,788 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-11-01 12:44:28,426 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 12:44:28,432 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 12:44:28,942 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-11-01 12:45:26,833 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-11-01 12:45:27,232 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2018-11-01 12:45:27,780 ERROR __main__ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 508, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 399, in main
    radio(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 222, in radio
    say("Tuning into " + name)
  File "/home/pi/GassistPi/src/actions.py", line 165, in say
    words= translator.translate(words, dest=language)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
2018-11-01 12:45:40,953 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 12:45:40,959 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 12:45:41,297 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-11-01 12:47:09,824 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-11-01 12:47:10,250 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2018-11-01 12:47:10,433 ERROR __main__ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 508, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 399, in main
    radio(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 222, in radio
    say("Tuning into " + name)
  File "/home/pi/GassistPi/src/actions.py", line 165, in say
    words= translator.translate(words, dest=language)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
2018-11-01 12:47:24,453 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 12:47:24,460 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 12:47:24,855 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-11-01 12:51:14,214 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-11-01 12:51:14,614 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2018-11-01 12:51:15,432 ERROR __main__ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 508, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 399, in main
    radio(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 222, in radio
    say("Tuning into " + name)
  File "/home/pi/GassistPi/src/actions.py", line 165, in say
    words= translator.translate(words, dest=language)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
2018-11-01 12:51:25,401 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 12:51:25,408 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 12:51:25,800 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-11-01 12:53:22,990 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-11-01 12:53:23,301 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2018-11-01 12:53:24,498 ERROR __main__ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 508, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 394, in main
    YouTube_No_Autoplay(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 1027, in YouTube_No_Autoplay
    say("Getting youtube link")
  File "/home/pi/GassistPi/src/actions.py", line 165, in say
    words= translator.translate(words, dest=language)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.4/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
2018-11-01 12:53:36,020 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-11-01 12:53:36,029 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com:443
2018-11-01 12:53:36,506 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None

**Comment by madmadda** [comment]
fixed it , it was token error google, it was thhe 504£ issue i think
