### ISSUE TITLE
assistant issue: google.protobuf not found

### ISSUE THREAD

**Issue by AjayD7890** [shivasiddharth/GassistPi#617]
### Describe the bug:
```
When completing the autostart service, I do not hear a noise or a "Hello." Also upon restarting the Pi, there is still no noise and there is still no response when I say OK google but the CPU shows it is at 25% use even when not being used. When I try to manually start the Google Assistant, I am told: ImportError: No module named 'google.protobuf' Also. the google assistant demo had worked so there is no issue with my speaker or mic.
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
Maybe

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
No

### 4. Is the assistant service restarting automatically?
No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```
no crash occured
```

### Paste the contents of the terminal below
```
pi@raspberrypi:~ $ /home/${USER}/env/bin/python -u /home/${USER}/GassistPi/src/main.py --device_model_id 'gass-4d225-gapp-ol5huo'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 40, in <module>
    from actions import say
  File "/home/pi/GassistPi/src/actions.py", line 15, in <module>
    from mediaplayer import api
  File "/home/pi/GassistPi/src/mediaplayer.py", line 7, in <module>
    from gmusicapi import Mobileclient
  File "/home/pi/env/lib/python3.5/site-packages/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/home/pi/env/lib/python3.5/site-packages/gmusicapi/clients/__init__.py", line 4, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "/home/pi/env/lib/python3.5/site-packages/gmusicapi/clients/webclient.py", line 16, in <module>
    from gmusicapi.clients.shared import _Base
  File "/home/pi/env/lib/python3.5/site-packages/gmusicapi/clients/shared.py", line 7, in <module>
    from gmusicapi.utils import utils
  File "/home/pi/env/lib/python3.5/site-packages/gmusicapi/utils/utils.py", line 24, in <module>
    from google.protobuf.descriptor import FieldDescriptor
ImportError: No module named 'google.protobuf'

```

**Comment by shivasiddharth** [comment]
Run the installer again.

**Comment by AjayD7890** [comment]
I tried running the "sudo chmod +x ./GassistPi/scripts/gassist-installer-pi3.sh" and everything else in the tutorial and I am still facing the same issue. Could this be an issue because I previously had the google assistant on the raspberry pi? Should I make a backup of the sd card and try again on new raspbian sd card?

**Comment by AjayD7890** [comment]
after getting a clean slate of raspbian, the google assistant started working! Thanks Sid
