### ISSUE TITLE
Parceltracking not working

### ISSUE THREAD

**Issue by oceank82** [shivasiddharth/GassistPi#620]
### Describe the bug:
```
Getting error when saying "track my parcel"
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes

### 4. Is the assistant service restarting automatically?
No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

nov 07 20:51:23 raspberrypi python[10243]:   {"text": "track my parcel"}
nov 07 20:51:25 raspberrypi python[10243]: ERROR:__main__:name 'parcelapi' is not defined
nov 07 20:51:25 raspberrypi python[10243]: Traceback (most recent call last):
nov 07 20:51:25 raspberrypi python[10243]:   File "/home/pi/GassistPi/src/main.py", line 672, in <module>
nov 07 20:51:25 raspberrypi python[10243]:     Myassistant().main()
nov 07 20:51:25 raspberrypi python[10243]:   File "/home/pi/GassistPi/src/main.py", line 540, in main
nov 07 20:51:25 raspberrypi python[10243]:     track()
nov 07 20:51:25 raspberrypi python[10243]:   File "/home/pi/GassistPi/src/actions.py", line 308, in track
nov 07 20:51:25 raspberrypi python[10243]:     text=parcelapi.trackings.get(tracking=dict(slug=slug, tracking_number=num
nov 07 20:51:25 raspberrypi python[10243]: NameError: name 'parcelapi' is not defined

```

**Comment by oceank82** [comment]
I solved it: the code is wrong so I changed the actions.py

From: 
parcelapi = aftership.APIv4('YOUR-AFTERSHIP-API-NUMBER')
couriers = parcelapi.couriers.all.get()

To: 
parcel = aftership.APIv4('YOUR-AFTERSHIP-API-NUMBER')
couriers = parcel.couriers.all.get()


Then it worked fine! case closed!
