### ISSUE TITLE
Snowboy does not work on OrangePi boards-- Need support for Orange Pi

### ISSUE THREAD

**Issue by BarryAlvord** [shivasiddharth/GassistPi#633]
i boot up assistant but end up with:
root@orangepizero:/home/pi# /home/pi/env/bin/python -u /home/pi/GassistPi/src/pushbutton.py --project-id raspbarry-d50b7-raspbarry-x5fsuh --device-model-id raspbarry-d50b7-raspbarry-x5fsuh
[01ac6f98] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
[01b06258] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/snowboydetect.py", line 15, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/GassistPi/src/pushbutton.py", line 60, in <module>
    import snowboydecoder
  File "/home/pi/GassistPi/src/snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/home/pi/GassistPi/src/snowboydetect.py", line 18, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pi/GassistPi/src/snowboydetect.py", line 17, in swig_import_helper
    return importlib.import_module('_snowboydetect')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
Please Help

**Comment by shivasiddharth** [comment]
As of now I support only builds on Raspberry Pi baords. Snowboy should be compiled fresh to work on Orange pi boards.
