### ISSUE TITLE
[RPi0][pushbutton.py] Asking "who are you" makes the assistant crashing

### ISSUE THREAD

**Issue by Darmur** [shivasiddharth/GassistPi#642]
### Describe the bug:
```
If I try to ask "who are you" to the assistant runnig on RPi0 from pushbutton.py, I have my system crashing and I need to restart the service to have it working again. Other commands works fine.
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes

### 4. Is the assistant service restarting automatically?
No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```
I've asked "who are you" to the assistant
```

### Paste the contents of the terminal below
```
pi@192.168.0.99's password:
Linux raspberrypi 4.14.79+ #1159 Sun Nov 4 17:28:08 GMT 2018 armv6l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Nov 22 14:22:09 2018 from 192.168.0.200
pi@raspberrypi:~ $ sudo systemctl stop gassistpi-push-button.service
pi@raspberrypi:~ $ /home/pi/env/bin/python -u /home/pi/GassistPi/src/pushbutton.py --project-id project-id --device-model-id saved-model-id
Initializing GPIOs 22 and 27 for assistant activity indication
what time is it
who are you
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/pushbutton.py", line 332, in assist
    selectedans=random.sample(configuration['Conversation']['answer'][i],1)
NameError: name 'random' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/GassistPi/src/pushbutton.py", line 970, in <module>
    main()
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/GassistPi/src/pushbutton.py", line 956, in main
    continue_conversation = assistant.assist()
  File "/home/pi/env/lib/python3.5/site-packages/tenacity/__init__.py", line 241, in wrapped_f
    return self.call(f, *args, **kw)
  File "/home/pi/env/lib/python3.5/site-packages/tenacity/__init__.py", line 330, in call
    start_time=start_time)
  File "/home/pi/env/lib/python3.5/site-packages/tenacity/__init__.py", line 279, in iter
    return fut.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/home/pi/env/lib/python3.5/site-packages/tenacity/__init__.py", line 333, in call
    result = fn(*args, **kwargs)
  File "/home/pi/GassistPi/src/pushbutton.py", line 336, in assist
    except Keyerror:
NameError: name 'Keyerror' is not defined

```

### Attach the log file. Log file can be found in /tmp directory. Remeber to copy your log file before shutting down or restarting the Pi.

I could not find any log in /tmp directory

**Comment by Darmur** [comment]
Adding "import random" at the beginning of pushbutton.py makes the crashing disappearing, but the assistant does not reply with an answer
