### ISSUE TITLE
[RPi0][pushbutton.py] "autoplay" is being recognized as "auto play", wrong function triggered

### ISSUE THREAD

**Issue by Darmur** [shivasiddharth/GassistPi#650]
**IMPORTANT NOTICE  
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.**  

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**    

### Describe the bug:
```
I tried to play a playlist from youtube, following the guidelines in the README.

I triggered my assistant with "Alexa, autoplay pink floyd playlist from youtube", but the voice recognizer system got "auto play" instead of "autoplay".

**auto play pink floyd playlist from youtube**

the part of code to determine whether to trigger YouTube_Autoplay() or YouTube_No_Autoplay() is looking for the string "autoplay"

                    if (custom_action_keyword['Keywords']['YouTube_music_stream'][0]).lower() in str(usrcmd).lower():
                        vlcplayer.stop_vlc()
                        if 'autoplay'.lower() in str(usrcmd).lower():
                            YouTube_Autoplay(str(usrcmd).lower())
                        else:
                            YouTube_No_Autoplay(str(usrcmd).lower())
                        return continue_conversation

because of that I can only trigger single tracks instead of list of tracks. every time I spell "autoplay" is being recognized as "auto play).

it would be great to have an update scripts able to handle both "autoplay" and "auto play", i can help here if needed

```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes

### 4. Is the assistant service restarting automatically?
No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

alexa, autoplay pink floyd playlist from youtube

```

### Paste the contents of the terminal below
```
pi@raspberrypi:~ $ /home/pi/env/bin/python -u /home/pi/GassistPi/src/pushbutton.py --project-id project-id --device-model-id saved-model-id
Initializing GPIOs 22 and 27 for assistant activity indication
INFO:snowboy:Keyword 1 detected at time: 2018-11-25 15:49:34
auto play pink floyd playlist from youtube
stopping vlc
Getting youtube link
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
        version 1.23.8; written and copyright by Michael Hipp and others
        free software (LGPL) without any warranty but with best wishes

Directory: /tmp/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: say.mp3 ...

MPEG 2.0 L III cbr32 24000 mono

[0:01] Decoding of say.mp3 finished.
pink floyd playlist
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ImportError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
https://r2---sn-5hne6nsr.googlevideo.com/videoplayback?keepalive=yes&c=WEB&mime=audio%2Fwebm&itag=251&pl=15&ei=osT6W5rrD43igQeola6gAw&ms=au%2Conr&mt=1543160872&mv=m&requiressl=yes&gir=yes&clen=4334926&mn=sn-5hne6nsr%2Csn-4g5e6nzs&fvip=2&source=youtube&initcwndbps=937500&id=o-ANET-_Rt_gyuojxFMIrrr0HyvCF0rGWY-wXMYWAsIsEr&dur=265.241&expire=1543182594&ip=87.212.212.139&key=yt6&lmt=1537431464654342&mm=31%2C26&ipbits=0&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&signature=630E9A96AC1788E9F86925CBA0DB56BFA1201BEF.DDC9E5B3642D2109F1AA348C6A95DB12FE93F01D&ratebypass=yes
INFO:snowboy:Keyword 1 detected at time: 2018-11-25 15:50:30
increase volume
INFO:snowboy:Keyword 1 detected at time: 2018-11-25 15:50:39
increase music volume
85
Setting volume to: 85
INFO:snowboy:Keyword 1 detected at time: 2018-11-25 15:50:52
auto play pink floyd playlist from youtube
stopping vlc
Getting youtube link
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
        version 1.23.8; written and copyright by Michael Hipp and others
        free software (LGPL) without any warranty but with best wishes

Directory: /tmp/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: say.mp3 ...

MPEG 2.0 L III cbr32 24000 mono

[0:01] Decoding of say.mp3 finished.
pink floyd playlist
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ImportError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
https://r4---sn-5hnednlr.googlevideo.com/videoplayback?requiressl=yes&initcwndbps=971250&key=yt6&gir=yes&mime=audio%2Fwebm&mt=1543160944&keepalive=yes&clen=6372648&dur=404.061&fvip=4&c=WEB&lmt=1540289946522097&ms=au%2Crdu&ei=6cT6W_jWMYfE1wLg54mIBg&mv=m&pl=15&ipbits=0&source=youtube&mn=sn-5hnednlr%2Csn-5hne6nsy&ip=87.212.212.139&id=o-AG-C6HZG1wxTskcgqtcboabxjG-I5V1OSrcGTOCTMwI3&expire=1543182665&mm=31%2C29&txp=5511222&itag=251&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&signature=36C3D3AF08D0DAA684CFF05324A6D08E8F6BC1FC.8394E3C5881914A2E6DCAD4973BA687E89C9EC5B&ratebypass=yes

```

**Comment by shivasiddharth** [comment]
You can change the `autoplay` to `auto play` here: https://github.com/shivasiddharth/GassistPi/blob/be4610de75f0facc2fd4c87198d5b42a5778d973/src/pushbutton.py#L386
