### ISSUE TITLE
ganna.com playback

### ISSUE THREAD

**Issue by saurabhtyagi2000** [shivasiddharth/GassistPi#666]
**IMPORTANT NOTICE  
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.**  

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**    

### Board and OS details:    
Open a terminal and run   
```
cat /proc/cpuinfo  
cat /etc/os-release  
```
```
Paste your Board and OS details here.   
```

### Describe the bug:
```

```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No

### If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes

### 4. Is the assistant service restarting automatically?
Yes

### If answer to question 4 is Yes, then paste the contents of the terminal below.

```ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "play playlist 1 from gaana.com"}
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "play playlist 1 from gaana.com"}
stopping vlc
Getting links for playlist number 1
Getting links for playlist number 1
WARNING:gtts.tts:Unable to get language list: 'NoneType' object is not subscriptable
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.23.8; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

Directory: /tmp/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: say.mp3 ...

MPEG 2.0 L III cbr32 24000 mono

[0:02] Decoding of say.mp3 finished.
50
Getting the tracks from Bollywood Top 50
WARNING:gtts.tts:Unable to get language list: 'NoneType' object is not subscriptable
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.23.8; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

Directory: /tmp/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: say.mp3 ...

MPEG 2.0 L III cbr32 24000 mono

[0:02] Decoding of say.mp3 finished.
Mera Pyar Tera Pyar Jalebi (Original Motion Picture Soundtrack)
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ImportError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
ERROR:__main__:<HttpError 400 when requesting https://www.googleapis.com/youtube/v3/search?q=Mera+Pyar+Tera+Pyar+Jalebi+%28Original+Motion+Picture+Soundtrack%29&alt=json&part=id%2Csnippet&key=HEREAIzaSyDU99c5HtVv0-M0DM51aaLMVyPRfcKqJJU returned "Bad Request">
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 692, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 680, in main
    gaana_playlist_select(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 1488, in gaana_playlist_select
    vlcplayer.gaana_player(currenttrackid)
  File "/home/pi/GassistPi/src/mediaplayer.py", line 203, in gaana_player
    urlid = youtube_search(tracks[trackid])
  File "/home/pi/GassistPi/src/youtube_search_engine.py", line 34, in youtube_search
    part='id,snippet'
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/http.py", line 842, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/youtube/v3/search?q=Mera+Pyar+Tera+Pyar+Jalebi+%28Original+Motion+Picture+Soundtrack%29&alt=json&part=id%2Csnippet&key=HEREAIzaSyDU99c5HtVv0-M0DM51aaLMVyPRfcKqJJU returned "Bad Request">



```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

**Comment by shivasiddharth** [comment]
You have exceeded the quota or usage limits of the free service. Wait for a day and try again.
