### ISSUE TITLE
Spotify error

### ISSUE THREAD

**Issue by Piflyer** [shivasiddharth/GassistPi#916]
### Board and OS details:    
Open a terminal and run   
```
cat /proc/cpuinfo  
cat /etc/os-release  
```
```
Paste your Board and OS details here.   
`processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 89.60
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 89.60
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 89.60
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 89.60
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2835
Revision        : a020d3
Serial          : 00000000954a8f56`

`PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"'

### Describe the bug:
```
Spotify gives me an error like this `/home/pi/env/lib/python3.5/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /home/pi/.local/share/gmusicapi/mobileclient.cred: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
2019-06-21 10:49:49,024 - gmusicapi.Mobileclient1 (shared:183) [WARNING]: could not retrieve oauth credentials from ''/home/pi/.local/share/gmusicapi/mobileclient.cred''
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/pushbutton.py", line 42, in <module>
    from actions import say
  File "/home/pi/GassistPi/src/actions.py", line 124, in <module>
    spotify_token = credentials.get_access_token()
  File "/home/pi/env/lib/python3.5/site-packages/spotipy/oauth2.py", line 63, in get_access_token
    token_info = self._request_access_token()
  File "/home/pi/env/lib/python3.5/site-packages/spotipy/oauth2.py", line 77, in _request_access_token
    raise SpotifyOauthError(response.reason)
spotipy.oauth2.SpotifyOauthError: Bad Request
`
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No

### 3. Does the assistant service start normally?
Yes/No

### 4. Is the assistant service restarting automatically?
No

### Manually start the assistant. For guidelines to start the assistant manually refer [this](https://github.com/shivasiddharth/GassistPi#manually-start-the-assistant)

### Paste the command below, that crashed the assistant
```
/home/pi/env/lib/python3.5/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /home/pi/.local/share/gmusicapi/mobileclient.cred: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
2019-06-21 10:49:49,024 - gmusicapi.Mobileclient1 (shared:183) [WARNING]: could not retrieve oauth credentials from ''/home/pi/.local/share/gmusicapi/mobileclient.cred''
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/pushbutton.py", line 42, in <module>
    from actions import say
  File "/home/pi/GassistPi/src/actions.py", line 124, in <module>
    spotify_token = credentials.get_access_token()
  File "/home/pi/env/lib/python3.5/site-packages/spotipy/oauth2.py", line 63, in get_access_token
    token_info = self._request_access_token()
  File "/home/pi/env/lib/python3.5/site-packages/spotipy/oauth2.py", line 77, in _request_access_token
    raise SpotifyOauthError(response.reason)
spotipy.oauth2.SpotifyOauthError: Bad Request
```

### Paste the contents of the terminal below
```
/home/pi/env/lib/python3.5/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /home/pi/.local/share/gmusicapi/mobileclient.cred: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
2019-06-21 10:49:49,024 - gmusicapi.Mobileclient1 (shared:183) [WARNING]: could not retrieve oauth credentials from ''/home/pi/.local/share/gmusicapi/mobileclient.cred''
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/pushbutton.py", line 42, in <module>
    from actions import say
  File "/home/pi/GassistPi/src/actions.py", line 124, in <module>
    spotify_token = credentials.get_access_token()
  File "/home/pi/env/lib/python3.5/site-packages/spotipy/oauth2.py", line 63, in get_access_token
    token_info = self._request_access_token()
  File "/home/pi/env/lib/python3.5/site-packages/spotipy/oauth2.py", line 77, in _request_access_token
    raise SpotifyOauthError(response.reason)
spotipy.oauth2.SpotifyOauthError: Bad Request
```

### Attach the log file named Gassistpi.log
Log file can be found in /tmp/ directory  
None are avaliable.

**Comment by Piflyer** [comment]
After enabling Google Play Music, I get this error `/home/${USER}/env/bin/python -u /home/${USER}/GassistPi/src/main.py --project-id 'aiypi-220700' --device_model_id 'aiypi-220700-smartdisplay-hmlpyj'
INFO:gmusicapi.Mobileclient1:!-- begin debug log --!
INFO:gmusicapi.Mobileclient1:version: 12.1.0
INFO:gmusicapi.Mobileclient1:logging to: /home/pi/.cache/gmusicapi/log/gmusicapi.log
INFO:gmusicapi.Mobileclient1:initialized
INFO:gmusicapi.Mobileclient1:logged out
INFO:gmusicapi.Mobileclient1:oauth successful
INFO:gmusicapi.Mobileclient1:authenticated
DEBUG:gmusicapi.Mobileclient1:Config(args=[], kwargs={'required_auth': [False, False, True, False]})
DEBUG:gmusicapi.Mobileclient1:{'kind': 'sj#configList', 'data': {'entries': [{'key': 'canManageFP', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'shouldShowLocalSuggestions', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'purchaseAccess', 'kind': 'sj#configEntry', 'value': '3'}, {'key': 'wsVdtMillis', 'kind': 'sj#configEntry', 'value': '30000'}, {'key': 'sideloadedPlaybackLogging', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'isWarmWelcomeDisabledForWoodstock', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'canCancelSubscription', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'nashvillebg', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'isVsAvailable', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'canBrowseSt', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'appstoreRatingPrompt', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'upsellDrawerCtaMessage', 'kind': 'sj#configEntry', 'value': 'SUBSCRIBE NOW'}, {'key': 'upsellDrawerDownloadMessage', 'kind': 'sj#configEntry', 'value': "Download and listen to any song, album, or station when you're not connected"}, {'key': 'wsVatMillis', 'kind': 'sj#configEntry', 'value': '5000'}, {'key': 'nuqRequiredForWsSignup', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'upsellSkipLimitTwoLeftCtaMessage', 'kind': 'sj#configEntry', 'value': 'GET MORE'}, {'key': 'upsellNewReleasesCtaMessage', 'kind': 'sj#configEntry', 'value': 'SUBSCRIBE'}, {'key': 'upsellListenNowCtaMessage', 'kind': 'sj#configEntry', 'value': 'SUBSCRIBE'}, {'key': 'enableWsExtras', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'upsellSignedOutMessage', 'kind': 'sj#configEntry', 'value': 'Subscribe to get millions of songs on-demand, offline, and ad-free'}, {'key': 'topListMaxSize', 'kind': 'sj#configEntry', 'value': '500'}, {'key': 'upsellSkipLimitTwoLeftMessage', 'kind': 'sj#configEntry', 'value': '2 skips left'}, {'key': 'showLMark', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'conciergeListenNow', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'minimumAppStartCountForFreeUpsell', 'kind': 'sj#configEntry', 'value': '6'}, {'key': 'upsellPreviousCtaMessage', 'kind': 'sj#configEntry', 'value': 'SUBSCRIBE'}, {'key': 'upsellDownloadMessage', 'kind': 'sj#configEntry', 'value': "Download and listen to any song, album, or station when you're not connected"}, {'key': 'showYoutubeRedInfoCard', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'concListenNow', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'instantSearchDelay', 'kind': 'sj#configEntry', 'value': '300'}, {'key': 'upsellChartsMessage', 'kind': 'sj#configEntry', 'value': 'Subscribe to play any song or album'}, {'key': 'isPodcastSyncEnabled', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'upsellChartsCtaMessage', 'kind': 'sj#configEntry', 'value': 'SUBSCRIBE'}, {'key': 'showViOSL', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'topListUpdatePeriodSeconds', 'kind': 'sj#configEntry', 'value': '604800'}, {'key': 'isSuggestDeletionEnabled', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'shouldShowServerSuggestions', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'situationsResponseTTLMinutes', 'kind': 'sj#configEntry', 'value': '30'}, {'key': 'isFoplessNautilusUser', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'appStartCountForFreeUpsellRevisionNumber', 'kind': 'sj#configEntry', 'value': '1459804296734'}, {'key': 'mgRPBDesc', 'kind': 'sj#configEntry', 'value': ''}, {'key': 'partridgeManagement', 'kind': 'sj#configEntry', 'value': '2'}, {'key': 'showB', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'showA', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'shouldEnableThriller', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'isPodcastsEnabledZ', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'upsellThumbsUpMessage', 'kind': 'sj#configEntry', 'value': 'Subscribe to play any song or album'}, {'key': 'topListPageSize', 'kind': 'sj#configEntry', 'value': '100'}, {'key': 'isHallmarkEnabled', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'upsellThumbsUpCtaMessage', 'kind': 'sj#configEntry', 'value': 'SUBSCRIBE'}, {'key': 'uploadAccess', 'kind': 'sj#configEntry', 'value': '3'}, {'key': 'isNautilusAvailable', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'nautilusAccess', 'kind': 'sj#configEntry', 'value': '2'}, {'key': 'isQuizEnabledForWoodstockOnSignup', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'showO', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'disabledConnectivityTimeoutMs', 'kind': 'sj#configEntry', 'value': '200000'}, {'key': 'hasPControlSettings', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'wasRecentlyInFoplessNautilus', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'showV', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'upsellSignedOutCtaMessage', 'kind': 'sj#configEntry', 'value': 'SUBSCRIBE'}, {'key': 'forceSignupFlow', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'isNautilusUser', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'isLNEnabled', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'wasEverInNautilus', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'ytContent', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'upsellSkipLimitOneLeftCtaMessage', 'kind': 'sj#configEntry', 'value': 'GET MORE'}, {'key': 'wsAatMillis', 'kind': 'sj#configEntry', 'value': '5000'}, {'key': 'partridgeAccess', 'kind': 'sj#configEntry', 'value': '2'}, {'key': 'warmWelcomeButtonText', 'kind': 'sj#configEntry', 'value': 'LISTEN_NOW'}, {'key': 'upsellPrerollVideoCtaMessage', 'kind': 'sj#configEntry', 'value': 'SUBSCRIBE'}, {'key': 'isTrAvailable', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'isInAppMessageEnabled', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'disableInfoCardsOnDayOne', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'partridgeUpsellTitle', 'kind': 'sj#configEntry', 'value': 'Unlimited music for you and your family'}, {'key': 'canRC', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'searchClusterResponseEnabled', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'upsellSkipLimitCtaMessage', 'kind': 'sj#configEntry', 'value': 'SUBSCRIBE'}, {'key': 'accountType', 'kind': 'sj#configEntry', 'value': 'Google Play Music Free'}, {'key': 'upsellPrerollVideoMessage', 'kind': 'sj#configEntry', 'value': 'Subscribe for all of the music on-demand and offline with none of the ads'}, {'key': 'upsellListenNowMessage', 'kind': 'sj#configEntry', 'value': 'Subscribe to get millions of songs on-demand, offline, and ad-free'}, {'key': 'partridgeUpsellBody', 'kind': 'sj#configEntry', 'value': 'Subscribe to Google Play Music family plan to give up to 6 people access to millions of songs, ad-free, for just $14.99/month.'}, {'key': 'isSuggestRequestEnabled', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'experimentIdsToLog', 'kind': 'sj#configEntry', 'value': '12600325,12600335,12600357,12600365,12600390,12600394,12600397,12600426,12600428,12600430,12600443,12600465,12600466,12600467,12600506,12600526,12600530,12600536,12602068,12604244,12604245,12604246,12611729,12612165,12612247,12616614,12616615,12617467,12619023,12619033,12619127,12620830,12625361,12625500,12625941,12626008,12626945,12627281,12627951,12628654,12629142,12629667,12630065,12630209,12631091,12631643,12632064,12632720,12633320,12634000,12635213,12636020,12641835,12641837,12642809,12643537,12648818,12648954,12649047,12650240,12650284,12650285,12652170,12653224,12653393,12653567,12655808,12656072,12656567,12657925,12658555,12658847,12660587,12661698,12664007,12664317,12664580,12665507,12666135,12667660,12667670,12669086,12669482,20350003,20350004,20350006'}, {'key': 'isExplicitRestrictedByPControl', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'isAnyServiceAvailable', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'pieDayOneCard', 'kind': 'sj#configEntry', 'value': 'NO_EXPERIMENT'}, {'key': 'upsellPreviousMessage', 'kind': 'sj#configEntry', 'value': 'Replay that song and millions of others, anytime'}, {'key': 'isAcceptedUser', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'appStartCountForFreeUpsell', 'kind': 'sj#configEntry', 'value': '250'}, {'key': 'wsAccess', 'kind': 'sj#configEntry', 'value': '3'}, {'key': 'fcapConfigJson', 'kind': 'sj#configEntry', 'value': '{\n  "userTenureIntervalWindow": {\n    "startMillis": "0",\n    "endMillis": "432000000"\n  },\n  "adsSessionConfig": [{\n    "sessionIntervalWindow": {\n      "startMillis": "0",\n      "endMillis": "3600000"\n    },\n    "firstAdOffsetMillis": "1740000",\n    "timeBetweenAdsMillis": "1740000"\n  }, {\n    "sessionIntervalWindow": {\n      "startMillis": "3600000",\n      "endMillis": "2592000000"\n    },\n    "firstAdOffsetMillis": "1740000",\n    "timeBetweenAdsMillis": "1740000"\n  }]\n}'}, {'key': 'androidTvEntityPageSize', 'kind': 'sj#configEntry', 'value': '10'}, {'key': 'isPlSharingEnabled', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'showLNInSettings', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'mgRPB', 'kind': 'sj#configEntry', 'value': 'Improve your recommendations'}, {'key': 'ytSubscriptionAccess', 'kind': 'sj#configEntry', 'value': '1'}, {'key': 'partridgeUpsellCallToAction', 'kind': 'sj#configEntry', 'value': 'LEARN MORE'}, {'key': 'upsellDrawerDownloadCtaMessage', 'kind': 'sj#configEntry', 'value': 'SUBSCRIBE'}, {'key': 'upsellSkipLimitOneLeftMessage', 'kind': 'sj#configEntry', 'value': '1 skip left'}, {'key': 'isDeviceVersionBlacklisted', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'wsPrefetchedAaeMillis', 'kind': 'sj#configEntry', 'value': '1800000'}, {'key': 'minimumGsaVersionRequiredForSoundSearch', 'kind': 'sj#configEntry', 'value': '300407000'}, {'key': 'isSoundSearchEnabled', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'podcastBrowseCategories', 'kind': 'sj#configEntry', 'value': '{"groups":[{"id":"JZCpodcasttopchart","displayName":"Top Charts"}]}'}, {'key': 'suggestRequestDelayMillis', 'kind': 'sj#configEntry', 'value': '150'}, {'key': 'partridgeUpsellDismissal', 'kind': 'sj#configEntry', 'value': 'NO THANKS'}, {'key': 'upsellSkipLimitMessage', 'kind': 'sj#configEntry', 'value': "You're out of skips. Get on-demand and offline access to millions of songs."}, {'key': 'upsellDownloadCtaMessage', 'kind': 'sj#configEntry', 'value': 'SUBSCRIBE'}, {'key': 'isInstantSearchEnabled', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'hasNewUserQuizPermission', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'upsellNewReleasesMessage', 'kind': 'sj#configEntry', 'value': 'Subscribe to play any song or album'}, {'key': 'persistentSubscriptionTrackUserLimit', 'kind': 'sj#configEntry', 'value': '100001'}, {'key': 'shouldValidateMediaRoutes', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'mediaRoutePackageSignatures', 'kind': 'sj#configEntry', 'value': '[{"packages": ["com.google.android.music", "com.google.android.setupwarlock", "com.google.android.gms"], "sha1s": ["38918A453D07199354F8B19AF05EC6562CED5788", "58E1C4133F7441EC3D2C270270A14802DA47BA0E"]}, {"packages": ["com.sonos.acr"], "sha1s": ["7387C9EB17CC5972F2B2FDF3E192884A78F24E7E", "62E2D848EF6FD0F8978F650D5DF9605786E26673", "9407A78494B106461537E1FC4E5D877E5ABCC7B3", "B6EA208733731F0CA8A123155830457C876130C4", "B703697E509B186616D83E978064A7A4F8D18775"]}]'}, {'key': 'enableFallbackForShortUrls', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'iosEnableStreamInterception', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'enableStructuredLogging', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'enableHttpsAlbumArt', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'isUpgradeTempCacheForKeeponEnabled', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'iosEnableCQ', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'castReceiverAppId', 'kind': 'sj#configEntry', 'value': '2872939A'}, {'key': 'iosHashCastAppContext', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'iosEnableWoodstockCloudQueue', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'iosEnableBackgroundDownloading', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'iosEnableRadioDownloads', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'iosRadioDownloadsAlwaysUseDownloadedSongs', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'iosRadioDownloadsEagerRefill', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'iosRadioDownloadsBatchSize', 'kind': 'sj#configEntry', 'value': '25'}, {'key': 'iosRadioDownloadsReadyPercent', 'kind': 'sj#configEntry', 'value': '80'}, {'key': 'iosEnableGPMAudioPlayer', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'iosEnableGPMAudioPlayerFMP4', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'enableAndroidChromecastCloudQueue', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'enableAndroidChromecastCloudQueueWoodstock', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'enableAndroidDialCloudQueue', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'iosEnableSonos', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'enableMpsOverride', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'enableReportAllPlayEventsInRealtime', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'askForNautilusCancellationReason', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'autoDogfoodStackCandidate', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'enableDGEvaluation', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'androidEnableAdaptiveHome', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'iosEnableAdaptiveHome', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'enableOkHttp', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'isSyncLoggingEnabled', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'enableOnePushSync', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'iosEnableOnepushNew', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'iosEnableGcmRegistrationNew', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'androidEnableEntitySuggest', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'iosEnableEntitySuggest', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'musicFeedbackLogs', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'isPrimesOdysseyEnabled', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'isPrimesClearcutEnabled', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'isPrimesMemoryEnabled', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'iosEnableStickyNav', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'androidEnableStickyNav', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'androidEnableAdaptiveHomeForMediaBrowser', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'androidEnableFastFirstTrack2', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'androidEnableDownloadLatencyLogging', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'enablePlayQualityIcon', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'androidEnableFmp4AacOnPlaybackV1', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'androidEnableFmp4AacOnPlaybackV2', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'iosMinimumBackgroundFetchIntervalSeconds', 'kind': 'sj#configEntry', 'value': '0'}, {'key': 'syncExperimentsToLogViaSyncService', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'androidEnableSilentFeedback', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'headphoneRecommendationNotification', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'androidEnableEntityBrowserForMediaBrowser', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'enableDynamicOffers', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'enableDynamicOffersWithCoupons', 'kind': 'sj#configEntry', 'value': 'false'}, {'key': 'disableULRReportingiOS', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'iosForegroundLocationFetchTimeoutMs', 'kind': 'sj#configEntry', 'value': '0'}, {'key': 'isBtAutoplaySettingEnabled', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'isWaitForSyncAfterSignupEnabled', 'kind': 'sj#configEntry', 'value': 'true'}, {'key': 'isPrimesCrashEnabled', 'kind': 'sj#configEntry', 'value': 'false'}]}}
DEBUG:gmusicapi.Mobileclient1:GetDeviceManagementInfo(args=[], kwargs={'required_auth': [False, False, True, False]})
DEBUG:gmusicapi.Mobileclient1:{'kind': 'sj#userClientIdList'}
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 51, in <module>
    from actions import say
  File "/home/pi/GassistPi/src/actions.py", line 14, in <module>
    from mediaplayer import api
  File "/home/pi/GassistPi/src/mediaplayer.py", line 27, in <module>
    if deviceid!=[]:
NameError: name 'deviceid' is not defined`
